Resources:
  demoServiceRole5E8D47D4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BackendStack/demo/ServiceRole/Resource
  demo9A46DC86:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1S3BucketBAC90272
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1S3VersionKey417A7CF2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1S3VersionKey417A7CF2
      Role:
        Fn::GetAtt:
          - demoServiceRole5E8D47D4
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      Runtime: nodejs12.x
    DependsOn:
      - demoServiceRole5E8D47D4
    Metadata:
      aws:cdk:path: BackendStack/demo/Resource
      aws:asset:path: /Users/akiyoshi/go/src/github.com/akira393/2021-cognito-webauthn-SimpleWebAuthn/backend/cdk.out/asset.c91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.87.1,@aws-cdk/assets=1.87.1,@aws-cdk/aws-applicationautoscaling=1.87.1,@aws-cdk/aws-autoscaling-common=1.87.1,@aws-cdk/aws-cloudwatch=1.87.1,@aws-cdk/aws-codeguruprofiler=1.87.1,@aws-cdk/aws-ec2=1.87.1,@aws-cdk/aws-ecr=1.87.1,@aws-cdk/aws-ecr-assets=1.87.1,@aws-cdk/aws-events=1.87.1,@aws-cdk/aws-iam=1.87.1,@aws-cdk/aws-kms=1.87.1,@aws-cdk/aws-lambda=1.87.1,@aws-cdk/aws-lambda-nodejs=1.87.1,@aws-cdk/aws-logs=1.87.1,@aws-cdk/aws-s3=1.87.1,@aws-cdk/aws-s3-assets=1.87.1,@aws-cdk/aws-sqs=1.87.1,@aws-cdk/aws-ssm=1.87.1,@aws-cdk/cloud-assembly-schema=1.87.1,@aws-cdk/core=1.87.1,@aws-cdk/cx-api=1.87.1,@aws-cdk/region-info=1.87.1,jsii-runtime=node.js/v12.14.1
    Metadata:
      aws:cdk:path: BackendStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1S3BucketBAC90272:
    Type: String
    Description: S3 bucket for asset "c91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1"
  AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1S3VersionKey417A7CF2:
    Type: String
    Description: S3 key for asset version "c91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1"
  AssetParametersc91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1ArtifactHash59F5121C:
    Type: String
    Description: Artifact hash for asset "c91c60aaaa34dc408ffa2a5fdd2898c23f80827a24f9ca4f704f325311f41dc1"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

